apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-filebeat-config
  namespace: default
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - /var/log/pods/*nginx*/*.log
        - /var/log/pods/*httpbin*/*.log

    output.elasticsearch:
      hosts: ["{{ .Values.elastic.endpoint }}"]
      username: "elastic"
      password: "{{ .Values.elastic.password }}"
      protocol: "https"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-filebeat
  namespace: default
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-filebeat
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-filebeat
      spec:
        terminationGracePeriodSeconds: 30
        containers:
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:8.12.0
          args: [
            "-c", "/etc/filebeat.yml",
            "-e",
          ]
          securityContext:
            runAsUser: 0
            privileged: true
          volumeMounts:
          - name: config
            mountPath: /etc/filebeat.yml
            subPath: filebeat.yml
          - name: varlog
            mountPath: /var/log
            readOnly: true
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true
        volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-filebeat-config
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers

