replicaCount: 4

image:
  repository: nginx
  tag: alpine
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
elastic:
  cloudId: "essu_WnpGWmFEZGhRVUk1YW1WRFpXbHVjbGRRTlZjNlUxaHVWR3RoUzNWNmVHUjBRak0xTVVsUU0xbE9kdz09AAAAAPDsQyc="
  password: "elastic"
