replicaCount: 4

image:
  repository: nginx
  tag: alpine
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  
elastic:
  cloudId: "https://my-elasticsearch-project-bf81b5.es.us-central1.gcp.elastic.cloud"
  password: "elastic"
