replicaCount: 4

image:
  repository: nginx
  tag: alpine
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  
elastic:
  cloudId: "bf81b53663ad49028313ab22b7db461a"
  password: "elastic"
